CREATE DATABASE e_commercecompanydb;
USE e_commercecompanydb;

-- CUSTOMERS TABLE
CREATE TABLE Customers(
CustomerID VARCHAR(100) PRIMARY KEY,
CustomerName VARCHAR(100),
Email VARCHAR(100),
City VARCHAR(100),
Phone BIGINT
);

INSERT  Customers(CustomerID,CustomerName,Email,City,Phone)
VALUES('C101','Rahul Sharma','rahul@gmail.com','Chennai',98760543210),
('C102','Priya Nair','priya2gmail.com','bangalore',99887766555),
('C103','Arjun Das','arjun@gmail.com','Hyderabad',NULL );


-- CATEGORIES
CREATE TABLE Categories(
CategoryID VARCHAR(100) PRIMARY KEY ,
CategoryName VARCHAR(100));

INSERT Categories(CategoryID,CategoryName)
VALUES('CAT01','Electronics'),
('CAT02','Fashion'),
('CAT03','Home Appliances');

-- PRODUCTS
CREATE TABLE Products(
ProductID VARCHAR(100) PRIMARY KEY,
ProductName VARCHAR(100),
Category VARCHAR(100),
Price INT,
StockQuantity INT );

INSERT Products(ProductID,ProductName,Category,Price,stockQuantity)
VALUES('P1001','iphone 15','Electronics',79999,15),
('P1002','Noise Headphones','Electronics',2999,50),
('P1003','Mens Jacket','Fashion',2499,30),
('P1004','Microwave Oven','Home Appliances',8999,12);


-- Orders
CREATE TABLE Orders(
OrderID VARCHAR(100) PRIMARY KEY,
CustomerID VARCHAR(100),
OrderDate DATE,
PaymentStatus VARCHAR(100),
FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
);

INSERT Orders(OrderID,CustomerID,OrderDate,PaymentStatus)
VALUES('O5001','C101','2026-05-10','Paid'),
('O5002','C102','2026-05-11','Pending'),
('O5003','C103','2026-05-12','Cancelled');

-- OrderDetails
CREATE TABLE OrderDetails(
OrderDetailID VARCHAR(100) PRIMARY KEY,
OrderID VARCHAR(100),
ProductID VARCHAR(100),
Quantity INT,
FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

INSERT OrderDetails(OrderDetailID,OrderID,ProductID,Quantity)
VALUES('OD01','O5001','P1001',1),
('OD02','O5002','P1003',2),
('OD03','O5003','P1002',1);

-- Employees
CREATE TABLE Employees(
EmployeeID VARCHAR(100) PRIMARY KEY,
EmployeeName VARCHAR(100) ,
Department VARCHAR(100)
);

INSERT Employees(EmployeeID,EmployeeName,Department)
VALUES('E101','Sneha Roy','Operations'),
('E102','Arjun Kumar','Sales');


-- Phase 3 — Business Queries & Filtering
-- The Sales Team requires quick operational reports.
-- Write SQL queries to answer the following business requirements:

-- 1.Find all customers from a particular city.
SELECT * FROM Customers;

-- 2.Display products within a given price range.
SELECT * FROM Products;

-- 3.Find orders placed between two dates.
SELECT * FROM Orders
WHERE OrderDate BETWEEN '2026-05-10' AND '2026-05-12';

-- 4.Search products using product name keywords.
SELECT * FROM Products
WHERE ProductName LIKE('M%');

-- 5.Identify customers without phone numbers.
SELECT * FROM Customers
WHERE Phone IS NULL;

-- 6.Display the top 5 highest-priced products.
SELECT ProductName,Price FROM Products
ORDER BY Price DESC
LIMIT 5;


-- 7.Show products sorted by price in descending order.
SELECT * FROM Products
ORDER BY Price DESC;


-- Phase 4 — Business Analysis & Aggregation
-- Management requires summarized insights for decision-making.
-- Generate reports for:

-- 1.Total sales generated by the company.
SELECT SUM(stockQuantity * Price) AS Total_sales FROM Products;

-- 2.Average product price category-wise.
SELECT ProductName , AVG(Price) AS Average_Product FROM Products
GROUP BY ProductName;

-- 3.Total number of orders placed by each customer.
SELECT CustomerID,COUNT(OrderID)FROM Orders
GROUP BY CustomerID;

-- 4.Highest-selling product.
SELECT ProductID,SUM(Quantity) AS Highest_sellingPrice FROM OrderDetails
GROUP BY ProductID
ORDER BY SUM(Quantity) DESC ;

-- 5.Category-wise revenue analysis.
SELECT Category,SUM(Price * StockQuantity) AS Revenue FROM Products
GROUP BY Category
ORDER BY SUM(Price * StockQuantity) DESC;

-- 6.Customers placing more than 3 orders.
-- 7.Monthly sales summary.
-- 8.Product category performance analysis.


-- Phase 5 — Multi-Table Analysis Using JOINS
-- The management team requires combined reports from multiple business departments.
-- Generate reports for:

-- 1.Customer details along with order information.
-- 2.Product details with category information.
-- 3.Orders handled by employees.
-- 4.Customers with pending payments.
-- 5.Products that were never ordered.
-- 6.Complete sales report including:
-- Customer Name
-- Product Name
-- Quantity
-- Order Date
-- Total Amount

